### PR TITLE
Updated openssl.c for OpenSSL-1.1.0 compatibility.

### PR DESCRIPTION
**Pull request by alexkrontiris**
COSE-c wouldn't build with OpenSSL-1.1.0. Some of the data structures used before have been made opaque. I have updated openssl.c to accomodate the changes.

### CODE REVIEW

**Comment by jimsch** [comment]
Can you make sure that you are checking for a null return on the calls to EVP_CIPHER_CTX_new or is that never going to fail the allocation?

**Comment by alexkrontiris** [comment]
I didn't find  any reason for the allocation to fail if the ctx is declared properly before calling EVP_CIPHER_CTX_new. In case of failure it returns null. I have added checks for every call made to EVP_CIPHER_CTX_new just in case. 

I noticed another possible issue. The ECDSA_SIG structures were never freed. That caused a small memory leak. It is fixed now. Do you agree that the sig should be freed at the end?

**Comment by jimsch** [comment]
Is there a package for 1.1 that can be loaded using apt?

**Comment by alexkrontiris** [comment]
I am afraid there isn't a package for 1.1.0 currently available in apt. The only option so far is to build it from source.

**Comment by jimsch** [comment]
I had to make a few changes so that it would continue to build with 1.0 version.  I haven't gotten setup to do a 1.1 build - so you might want to verify that I did not mess things up.  I will look at getting an CI build of 1.1 running at some point.

**Pull request merged**
